services: 
  backend:
    user: root
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    env_file:
      - apps/backend/.env
    environment:
      - NODE_ENV: ${NODE_ENV}
      - DB_NAME: ${DB_NAME}
      - DB_HOST: ${DB_HOST}
      - DB_USER: ${DB_USER}
      - DB_PASSWORD: ${DB_PASSWORD}
      - ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      - REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      - DB_ENCRYPT_SECRET: ${DB_ENCRYPT_SECRET}
      - DB_HASH_PEPPER: ${DB_HASH_PEPPER}
      - FRONTEND_URL: ${FRONTEND_URL}
      - MAIL_HOST: ${MAIL_HOST}
      - MAIL_PORT: ${MAIL_PORT}
      - MAIL_USER: ${MAIL_USER}
      - MAIL_PASS: ${MAIL_PASS}
    restart: unless-stopped
    volumes:
      - data:/data
   
  nginx:
    image: nginx:alpine
    volumes:
      - data:/data:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports: 
      - 80:80


volumes:
  data: