services: 
  backend:
    restart: unless-stopped
    user: root
    build:
      context: .
      dockerfile: apps/backend/Dockerfile

    volumes:
      - data:/immersia/data

    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DB_NAME: ${DB_NAME}
      DB_HOST: ${DB_HOST}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
      REFRESH_TOKEN_SECRET: ${REFRESH_TOKEN_SECRET}
      DB_ENCRYPT_SECRET: ${DB_ENCRYPT_SECRET}
      DB_HASH_PEPPER: ${DB_HASH_PEPPER}
      FRONTEND_URL: ${FRONTEND_URL}
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT}
      MAIL_USER: ${MAIL_USER}
      MAIL_PASS: ${MAIL_PASS}

    labels:
      - "traefik.enable=true"

      - "traefik.http.routers.immersia-backend.rule=Host(`${HOSTNAME}`) && PathPrefix(`/api`)"
      - "traefik.http.routers.immersia-backend.entrypoints=websecure"
      - "traefik.http.routers.immersia-backend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.immersia-backend.tls=true"

      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
      - "traefik.http.routers.immersia-backend.middlewares=strip-api"

      - "traefik.http.services.immersia-backend.loadbalancer.server.port=${PORT}"

      - "traefik.docker.network=shared-proxy"

    networks:
      - shared-proxy
      - shared-db

   
  frontend:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    restart: unless-stopped
    networks:
      - shared-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.immersia-frontend.rule=Host(`${HOSTNAME}`)"
      - "traefik.http.routers.immersia-frontend.entrypoints=websecure"
      - "traefik.http.routers.immersia-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.routers.immersia-frontend.tls=true"
      - "traefik.http.services.immersia-frontend.loadbalancer.server.port=80"
      - "traefik.docker.network=shared-proxy"
    volumes:
      - data:/immersia/data:ro


volumes:
  data:

networks:
  shared-proxy:
    external: true
  shared-db:
    external: true
