
worker_processes  1;


events {
    worker_connections  1024;
}


http {
    client_max_body_size 500M;
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;

    # server {
    #     listen       80 default_server;


    #     location / {
    #         root    ../frontend/;
    #         index   index.html;
    #     }
    # }

    server {
        listen 80;
        server_name api.*;

        location / {
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_pass http://backend:3000/;
        }  
        location /internal/ {
            internal;
            alias /data/;
            add_header Access-Control-Allow-Origin *;
            add_header Accept-Ranges bytes;
        } 
    }
}
